### ISSUE TITLE
How to ignore RMAC checks?

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [schierlm/BibleMultiConverter#17]
I am converting modules from MyBible, that have non standard morphology tags, and these get dropped because they do not match your RMAC check patterns.

Is it possible to add an option for turning off RMAC check while converting from MyBible?

**Comment by schierlm** [comment]
Are you talking about MyBible.zone (which uses a SQLite based format) or MyBible.de (which uses a Zefania XML variant)?

Could you share a sample module?

Also, what format are you trying to convert to? The code for some formats (e.g. Logos) contains logic to convert RMAC to the format's native morphology format, which could probably crash if an invalid morph tag is encountered. Other formats perform a XSD validation after export, which will fail in case the RMAC tag does not match the definition. 

That's why ignoring the RMAC check is only half of the fix.

An option would be to convert invalid morph tags to xattr instead of grammar attributes, which the target format would also have to support (if it is possible in the target format to output "invalid" RMACs.) Other formats would then ignore the xattr during export - so the ignoring is moved from the import to the export stage.

**Comment by schierlm** [comment]
I now added an option to MyBibleZone to parse `<m>` (and if desired also `<f>`) tags to extra attributes, which do not get validated, but get converted back in case you convert to the same format, but get ignored when converting to other formats (except the internal formats Compact, Diffable, etc.). See the commit for an example command how to use.

In case this does not fix your issue, feel free to reopen.

**Comment by schierlm** [comment]
Continued in #30
