### ISSUE TITLE
mvn build fails with jaxb

### ISSUE THREAD

**Issue by lexiconwriter** [schierlm/BibleMultiConverter#2]
[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate (generate) on project BibleMultiConverter-schemas: Execution generate of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate: com/sun/xml/bind/api/ErrorListener

I guess the jaxb version is wrong:

http://search.maven.org/#search%7Cga%7C1%7Corg.jvnet.jaxb2.maven2

But I can't find 0.12.3 there. So I changed the version to 0.13.1 but then I get:

[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate (generate) on project BibleMultiConverter-schemas: Execution generate of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate: com/sun/xml/bind/api/ErrorListener
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: d:\Users\Oliver\apache-maven-3.3.9\bin\..
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: c:\PROGRA~2\Java\jre1.8.0_101
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "x86", family: "dos"

**Comment by schierlm** [comment]
Your `JAVA_HOME` points to a JRE install. Even if you were able to build the JAXB stubs, the compile phase would fail as the JRE does not include a compiler.

I will download and re-test with JDK 1.8.0 update 101 (my JDK is quite a bit older) but I assume that it should work fine if you point JAVA_HOME to your JDK instead of your JRE.

**Comment by schierlm** [comment]
Just tested a fresh checkout of this repo with an empty `.m2` repository with JDK 1.8.0_101 and maven 3.3.9, and it worked fine when skipping the SWORD edition (because the SWORD edition depends on a snapshot of jsword that does not seem to exist in any repo any more...)

If you want the SWORD edition, probably take the library from the released binary version of BibleMultiConverter and add it to your local Maven repo.

If there are any more problems, feel free to re-open the issue.

**Comment by lexiconwriter** [comment]
Okay, now it works better :) On SWORD format I will work later and check to include the jar class directly. 

One short XML format question:

I have an old bible format in my archive looking like this:

<PARSERINFO ENCODE="iso-8859-1" WORDTYPE="SPCSEP">
<BIBLE name="GN" INFO="Gute Nachricht">
<BOOK NAME="Hoheslied" NUMBER="260" SHORTCUT="Hoh">
<CHAPTER><VERSE><BOOKTEXT>HOHESLIED<CHAPTEXT>Kapitel 1<VERSTEXT>Das schönste aller Lieder, von Salomo.</VERSE>

Can you tell me please which format it is? I would appreciate that very much. Many years ago I converted it with a converter into palmbible+. Unfortunetaly I can't find the converter and the files anymore. And Palm I don't use anymore.

**Comment by lexiconwriter** [comment]
Okay, now it works better :) On SWORD format I will work later and check to
include the jar class directly.

One short XML format question:

I have an old bible format in my archive looking like this:

<PARSERINFO ENCODE="iso-8859-1" WORDTYPE="SPCSEP">
<BIBLE name="GN" INFO="Gute Nachricht">
<BOOK NAME="Hoheslied" NUMBER="260" SHORTCUT="Hoh">
<CHAPTER><VERSE><BOOKTEXT>HOHESLIED<CHAPTEXT>Kapitel 1<VERSTEXT>Das
schönste aller Lieder, von Salomo.</VERSE>

Can you tell me please which format it is? I would appreciate that very
much. Many years ago I converted it with a converter into palmbible+.
Unfortunetaly I can't find the converter and the files anymore. And Palm I
don't use anymore.

2016-09-28 22:35 GMT+02:00 Michael Schierl <notifications@github.com>:

**Comment by schierlm** [comment]
Hello lexiconwriter,

Am 29.09.2016 um 11:58 schrieb lexiconwriter:

> I have an old bible format in my archive looking like this:
> 
> <PARSERINFO ENCODE="iso-8859-1" WORDTYPE="SPCSEP">
> <BIBLE name="GN" INFO="Gute Nachricht">
> <BOOK NAME="Hoheslied" NUMBER="260" SHORTCUT="Hoh">
> <CHAPTER><VERSE><BOOKTEXT>HOHESLIED<CHAPTEXT>Kapitel 1<VERSTEXT>Das
> schönste aller Lieder, von Salomo.</VERSE>
> 
> Can you tell me please which format it is?

It's the import format used by YCHBibleConverter, found at
https://sourceforge.net/projects/palmbibleplus/files/zBibleConverter/YCH/

I don't think it has its own name, it is not even valid XML (<VERSTEXT>
tags are never closed).

BibleMultiConverter can currently export to that format, but not import
it again, since I never found any bibles in that format, and since
exporting to that format loses almost all information (except for
unformatted headlines and unformatted verse texts).

If there is any need, I could add import support to that format as well
(or you can do it and submit a Pull Request).


Hope this helps,


Michael
