### ISSUE TITLE
NullPointerException when pointing USFM/USX import to file instead of directory

### ISSUE THREAD

**Issue by teusbenschop** [schierlm/BibleMultiConverter#21]
Hello

While converting USFM data to the QuickBible format, the converter gives this output:

```
Exception in thread "main" java.lang.NullPointerException
	at biblemulticonverter.format.paratext.AbstractParatextFormat.doImportAllBooks(AbstractParatextFormat.java:263)
	at biblemulticonverter.format.paratext.AbstractParatextFormat.doImportBooks(AbstractParatextFormat.java:211)
	at biblemulticonverter.format.paratext.AbstractParatextFormat.doImport(AbstractParatextFormat.java:55)
	at biblemulticonverter.Main.main(Main.java:66)
```

The java version is this:
```
$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

The command line for conversion is this:

```
$ java -jar BibleMultiConverter/biblemulticonverter/target/BibleMultiConverter-0.0-SNAPSHOT-dist/BibleMultiConverter.jar USFM 00_Bible/03_Genesis.usfm QuickBible out.yet
```

The USFM file is this:
[03_Genesis.usfm.zip](https://github.com/schierlm/BibleMultiConverter/files/2854973/03_Genesis.usfm.zip)

How can I successfully convert the input USFM to the output .yet file?

**Comment by schierlm** [comment]
Thank you for the bug report. I need to make it clearer that USFM import (as well as USX) requires you to give the **directory with .usfm files** as input parameter (it is mentioned in the help text for the import filter, but throwing NullPointerException is not nice anyway.

So, instead of this

    java -jar BibleMultiConverter/biblemulticonverter/target/BibleMultiConverter-0.0-SNAPSHOT-dist/BibleMultiConverter.jar USFM 00_Bible/03_Genesis.usfm QuickBible out.yet

try this

    java -jar BibleMultiConverter/biblemulticonverter/target/BibleMultiConverter-0.0-SNAPSHOT-dist/BibleMultiConverter.jar USFM 00_Bible QuickBible out.yet

and it will create you a YET file for the whole bible (not only Genesis). I tested it with a directory with just Genesis in it, and it worked for me.

I will leave this issue open to track the required changes to return a proper error message instead.

**Comment by teusbenschop** [comment]
Thank you for the solution to this problem so it no longer crashes.
