### ISSUE TITLE
Error during installation of BibleMultiConvertor All in One Edition

### ISSUE THREAD

**Issue by amrhone** [schierlm/BibleMultiConverter#59]
Hello, I'm having trouble installing BibleMultiConvertor All in One Edition. I verified that Java is installed on my PC but when I run "java -jar BibleMultiConverter.jar" on the command line I get the following error "Error: Unable to access jarfile BibleMultiConvertor.jar". Any help with this issue would be greatly appreciated.

**Comment by schierlm** [comment]
Hello,

The file name of the All-in-One-Edition is `BibleMultiConverter-AllInOneEdition.jar`, so you should run `java -jar BibleMultiConverter-AllInOneEdition.jar`.

Also make sure that you are in the correct directory, so that `dir` (Windows) or `ls` (Unix) will actually show you the jar file.

Hope this helps.

**Comment by amrhone** [comment]
Thank you for the response @schierlm. I moved the file to the correct directory (I didn't have it in the correct one previously) but now I'm getting the following error when I try to run it:
 `Error: Could not find or load main class biblemulticonverter.Main
Caused by: java.lang.ClassNotFoundException: biblemulticonverter.Main`

**Comment by schierlm** [comment]
Please don't move one file without moving the rest. In this case its `lib` direcctory is missing.

**Comment by amrhone** [comment]
@schierlm that resolved the issue. Thank you!
