### ISSUE TITLE
USFM `\fig` properties written out as plain text

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#68]
I see some USFM tags like `\fig` aren't supported, which is understandable. Though at the moment they appear to be written out as plain text:

`\v 6 Na omiu hinage Loma Yaubada bada iyogaegomiu'o ta omiu Yeisu Besinana yana boda ainai ammiyamiya. \fig Rom 1.7|src="hk00237b.tif" size="col" ref="Loma 1:6" \fig*`

goes to:

`<verse number="6" style="v" sid="ROM 1:6"/>Na omiu hinage Loma Yaubada bada iyogaegomiu'o ta omiu Yeisu Besinana yana boda ainai ammiyamiya. Rom 1.7|src="hk00237b.tif" size="col" ref="Loma 1:6"<verse eid="ROM 1:6"/>`

Is there an option to just exclude them entirely?

([example is from Romans 1:6](https://ebible.org/Scriptures/kud2014_usfm.zip))

**Comment by schierlm** [comment]
Due to the fact that tag structure in USFM is not as unified as you might like, it would require special casing for the "unsupported" tags. Currently, everything from the backslash to the first non-letter character is skipped. For `\fig`, you would probably want to skip to the next `\fig*`, yet for `\qs-s` you will probably skip to either the following '\*` or to the '\*` after the next `\qs-e`.

That being said, I am not interested in implementing these (or any other) advanced USFM tags, not even to the extent to improve skipping them. If anyone wants to tackle this, patches are of course welcome.

**Comment by Rolf-Smit** [comment]
I may be able to work on this, I have some custom software for my Bible app that can handle these open and close tags, including nesting. However I'm not sure how much work it would be to get that I to this.

I also have a USFM tool that I call a cleaner/normalizer, that is able to filter out these tags from USFM files.

Maybe I could opensource that and you (@shadow-light) would be able to filter them out, is that sufficient?

But I need some time to look into both things.

**Comment by shadow-light** [comment]
No problem, yes I'm happy to help work on this. If it is fairly simple I could do a PR for this tool. Or if it's complex, a tool to normalize USFM before passing to BibleMultiConverter could also be good.

**Comment by schierlm** [comment]
The tag names themselves, i.e, `\fig` or `\va` get skipped. Their arguments get written out as plain text. And a warning is issued.

So, in the example from the documentation

    \v 1 \va 3\va* Save me by your power, O God;

The number 3 will become part of the verse text of verse 1.

**Comment by schierlm** [comment]
I believe this issue can be closed now. With 55ddf97a30cf912cdd0722751149738b7ed5fd0e, `\fig` (both the old USFM2 and the new word-level-attribute USFM3 formats) can be read and written out to USFM and USX2/3. Conversion to other non-HTML-based formats loses everything except the caption, but that may get improved with #93.
