### ISSUE TITLE
Bibleworks to theword

### ISSUE THREAD

**Issue by WJSwan1945** [schierlm/BibleMultiConverter#81]
To convert a Bibleworks bible to TheWord do I input the .bww that I export from Bibleworks?

**Comment by schierlm** [comment]
I never used BibleWorks, so I cannot tell you what file extensions it uses for what. Bibles for BibleWorks can either be in binary format (Version Database), in text format or in RTF format. If you can export your bible in text or RTF format, you can use the `BibleWorks` or `BibleWorksRTF` input format to conert to e.g. TheWord. When your bible cannot be exported in one of those formats (e.g. because it is copyrighted), you cannot convert it.
